// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	UserID uint   `json:"userID"`
	Text   string `json:"text"`
}

type Todo struct {
	ID   uint   `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type User struct {
	ID             uint      `json:"id"`
	DisplayID      string    `json:"displayID"`
	IsUnsubscribed bool      `json:"isUnsubscribed"`
	Nickname       string    `json:"nickname"`
	Birthday       time.Time `json:"birthday"`
	Todos          []*Todo   `json:"todos"`
}
