// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID             string    `json:"id"`
	DisplayID      string    `json:"displayID"`
	IsUnsubscribed bool      `json:"isUnsubscribed"`
	Nickname       string    `json:"nickname"`
	Birthday       time.Time `json:"birthday"`
	Todos          []*Todo   `json:"todos"`
}
